import type { MenuItem, RecommendedVendor } from "@/lib/types/database";
import { MOCK_VENDOR_IMAGES } from "@/lib/vendor-images";

export const DEMO_VENDORS: RecommendedVendor[] = [
  {
    id: "11111111-1111-1111-1111-111111111101",
    name: "Tacos El Güero",
    location_name: "Colonia Roma Norte",
    city: "CDMX",
    latitude: 19.42,
    longitude: -99.15,
    capacity_total: 20,
    available: 18,
    tags: ["Traditional", "Beef", "Spicy"],
    image_url: MOCK_VENDOR_IMAGES[0],
    distance_km: 0,
    score: 0,
    menus: [
      {
        id: "m1",
        vendor_id: "11111111-1111-1111-1111-111111111101",
        item_name: "Tacos de Suadero",
        description_original: "Tacos de suadero con cebolla y cilantro",
        description_translated:
          "Beef brisket tacos (suadero is slow-cooked beef) with onion and cilantro",
        price: 35,
        tags: ["Beef", "Traditional"],
        created_at: new Date().toISOString(),
      },
      {
        id: "m2",
        vendor_id: "11111111-1111-1111-1111-111111111101",
        item_name: "Tacos al Pastor",
        description_original: "Tacos al pastor con piña y salsa roja",
        description_translated:
          "Marinated pork tacos with pineapple and red salsa — a Mexico City classic",
        price: 40,
        tags: ["Pork", "Spicy", "Traditional"],
        created_at: new Date().toISOString(),
      },
    ] as MenuItem[],
  },
  {
    id: "11111111-1111-1111-1111-111111111102",
    name: "Tlayudas Oaxaqueñas Doña Lupita",
    location_name: "Coyoacán",
    city: "CDMX",
    latitude: 19.35,
    longitude: -99.08,
    capacity_total: 15,
    available: 12,
    tags: ["Vegetarian", "Traditional", "Vegan"],
    image_url: MOCK_VENDOR_IMAGES[1],
    distance_km: 0,
    score: 0,
    menus: [
      {
        id: "m3",
        vendor_id: "11111111-1111-1111-1111-111111111102",
        item_name: "Tlayuda Clásica",
        description_original: "Tlayuda con frijol, quesillo y tasajo",
        description_translated:
          "Large crispy Oaxacan tortilla with beans, Oaxaca cheese and dried beef",
        price: 85,
        tags: ["Traditional"],
        created_at: new Date().toISOString(),
      },
      {
        id: "m4",
        vendor_id: "11111111-1111-1111-1111-111111111102",
        item_name: "Tlayuda Vegana",
        description_original: "Tlayuda con frijol, nopales y aguacate",
        description_translated:
          "Vegan tlayuda with beans, cactus and avocado",
        price: 75,
        tags: ["Vegan", "Vegetarian"],
        created_at: new Date().toISOString(),
      },
    ] as MenuItem[],
  },
  {
    id: "22222222-2222-2222-2222-222222222201",
    name: "Birrieria El Compadre",
    location_name: "Centro Histórico",
    city: "Guadalajara",
    latitude: 20.67,
    longitude: -103.34,
    capacity_total: 25,
    available: 20,
    tags: ["Traditional", "Beef"],
    image_url: MOCK_VENDOR_IMAGES[2],
    distance_km: 0,
    score: 0,
    menus: [
      {
        id: "m5",
        vendor_id: "22222222-2222-2222-2222-222222222201",
        item_name: "Birria de Res",
        description_original: "Birria estilo Jalisco con consomé",
        description_translated:
          "Slow-stewed beef birria with rich consommé broth — Jalisco specialty",
        price: 120,
        tags: ["Beef", "Traditional"],
        created_at: new Date().toISOString(),
      },
    ] as MenuItem[],
  },
  {
    id: "22222222-2222-2222-2222-222222222202",
    name: "Tortas Ahogadas La Chiva",
    location_name: "Mercado Libertad",
    city: "Guadalajara",
    latitude: 20.65,
    longitude: -103.35,
    capacity_total: 18,
    available: 15,
    tags: ["Spicy", "Pork", "Traditional"],
    image_url: MOCK_VENDOR_IMAGES[3],
    distance_km: 0,
    score: 0,
    menus: [
      {
        id: "m6",
        vendor_id: "22222222-2222-2222-2222-222222222202",
        item_name: "Torta Ahogada",
        description_original: "Torta ahogada con carnitas y salsa picante",
        description_translated:
          "Drowned sandwich with carnitas pork in spicy tomato sauce — Guadalajara icon",
        price: 55,
        tags: ["Pork", "Spicy"],
        created_at: new Date().toISOString(),
      },
    ] as MenuItem[],
  },
  {
    id: "33333333-3333-3333-3333-333333333301",
    name: "Cabrito Don Ramón",
    location_name: "Barrio Antiguo",
    city: "Monterrey",
    latitude: 25.67,
    longitude: -100.31,
    capacity_total: 30,
    available: 25,
    tags: ["Traditional", "Goat"],
    image_url: MOCK_VENDOR_IMAGES[4],
    distance_km: 0,
    score: 0,
    menus: [
      {
        id: "m7",
        vendor_id: "33333333-3333-3333-3333-333333333301",
        item_name: "Cabrito al Horno",
        description_original: "Cabrito al horno estilo Monterrey",
        description_translated:
          "Slow-roasted young goat — Monterrey's signature dish",
        price: 250,
        tags: ["Goat", "Traditional"],
        created_at: new Date().toISOString(),
      },
    ] as MenuItem[],
  },
  {
    id: "33333333-3333-3333-3333-333333333302",
    name: "Elotes y Esquites La Güera",
    location_name: "Parque Fundidora",
    city: "Monterrey",
    latitude: 25.69,
    longitude: -100.29,
    capacity_total: 12,
    available: 10,
    tags: ["Vegetarian", "Vegan"],
    image_url: MOCK_VENDOR_IMAGES[5],
    distance_km: 0,
    score: 0,
    menus: [
      {
        id: "m8",
        vendor_id: "33333333-3333-3333-3333-333333333302",
        item_name: "Esquites",
        description_original: "Esquites con mayonesa, chile y limón",
        description_translated:
          "Cup of corn kernels with mayo, chili powder and lime — classic street snack",
        price: 45,
        tags: ["Vegetarian"],
        created_at: new Date().toISOString(),
      },
      {
        id: "m9",
        vendor_id: "33333333-3333-3333-3333-333333333302",
        item_name: "Elote Vegano",
        description_original: "Elote con mantequilla vegana y chile",
        description_translated:
          "Grilled corn on the cob with vegan butter and chili — plant-based option",
        price: 40,
        tags: ["Vegan", "Vegetarian"],
        created_at: new Date().toISOString(),
      },
    ] as MenuItem[],
  },
];

export const DEMO_SEED_VENDORS = DEMO_VENDORS.map((v) => ({
  name: v.name,
  location_name: v.location_name,
  city: v.city,
  latitude: v.latitude,
  longitude: v.longitude,
  capacity_total: v.capacity_total,
  hours: {
    mon: "10-22",
    tue: "10-22",
    wed: "10-22",
    thu: "10-22",
    fri: "10-23",
    sat: "10-23",
    sun: "11-21",
  },
  tags: v.tags,
  image_url: v.image_url ?? null,
  menus: v.menus.map((m) => ({
    item_name: m.item_name,
    description_original: m.description_original,
    description_translated: m.description_translated,
    price: m.price,
    tags: m.tags,
  })),
}));
